version: 2
jobs:
        build:
                docker:
                - image: busybox:latest
                steps:
                - run:
                        name: Hello World
                        command: echo "Hello World"
